### ISSUE TITLE
YamlReader is not working as expected

### ISSUE THREAD

**Issue by cmungall** [phenopackets/phenopacket-reference-implementation#16]
Is inheritance always followed? The id field does not appear to be populated

**Comment by julesjacobsen** [comment]
This is partly related to https://github.com/phenopackets/phenopacket-format/issues/32 

The underlying issue is that Jackson doesn't know what it's supposed to be creating as YAML requires a type e.g. ```!<person>``` in order to know what it needs to deserialise as.
```yaml
entities:
- !<person>
  strain: null
  types: null
  negated_types: null
  description: null
  id: "person#1"
  label: "Joe Bloggs"
  taxon: null
  sex: null
  date_of_birth: null
- !<variant>
  descriptionHGVS: "c.1234A>G"
  id: "variant#1"
  label: "c.1234A>G"
phenotype_profile:
- phenotype: !<phenotype>
    measurements: null
    types:
    - id: "HP:0200055"
      label: "Small hands"
    negated_types: null
    description: null
    has_location: null
    onset: null
    offset: null
    severity: null
    environment: null
  entity: !<person>
    strain: null
    types: null
    negated_types: null
    description: null
    id: "person#1"
    label: "Joe Bloggs"
    taxon: null
    sex: null
    date_of_birth: null
  evidence:
  - types:
    - id: "ECO:0000033"
      label: "TAS"
    negated_types: null
    description: null
    supporting_entities: null
    source:
    - "PMID:23455423"
```

JSON uses a "type" key to acheive the same thing. 

You want to be able to do use YAML tags of sorts, but only ever refer to the id of an entity once defined:

```yaml
entities:
- id: "person#1"
  type: person
  strain: null
  types: null
  negated_types: null
  description: null
  label: "Joe Bloggs"
  taxon: null
  sex: null
  date_of_birth: null
- id: "variant#1"
  descriptionHGVS: "c.1234A>G"
  type: variant
  label: "c.1234A>G"
phenotype_profile:
- entity: "person#1"
  phenotype:
    measurements: null
    types:
    - id: "HP:0200055"
      label: "Small hands"
    negated_types: null
    description: null
    has_location: null
    onset: null
    offset: null
    severity: null
    environment: null  
  evidence:
  - types:
    - id: "ECO:0000033"
      label: "TAS"
    source:
    - "PMID:23455423"
```
Plus I guess you don't want the keys with null values written out either.

**Comment by julesjacobsen** [comment]
This is now read as expected:

```yaml
---
id: "phenopkt#1"
title: "Patient X phenotypes and potentially causative variant"
persons:
- id: "person#1"
  label: "Joe Bloggs"
  sex: "M"
variants:
- id: "variant#1"
  descriptionHGVS: "c.1234A>G"
  label: "c.1234A>G"
phenotype_profile:
- entity: "person#1"
  phenotype:
    types:
    - id: "HP:0200055"
      label: "Small hands"
  evidence:
  - types:
    - id: "ECO:0000033"
      label: "TAS"
    source:
    - id: "PMID:23455423"
```
