### ISSUE TITLE
Don't write keys with null values in YAML/JSON output

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-reference-implementation#18]
```yaml
entities:
- !<person>
  strain: null
  types: null
  negated_types: null
  description: null
  id: "person#1"
  label: "Joe Bloggs"
  taxon: null
  sex: null
  date_of_birth: null
```

should be written as

```yaml
entities:
- !<person>
  id: "person#1"
  label: "Joe Bloggs"
```
